# Copyright 2019 The Grin Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trigger:
  branches:
    include:
      - master
  tags:
    include: ['*']

pr:
  branches:
    include: ['*']

variables:
  RUST_BACKTRACE: '1'
  RUSTFLAGS: '-C debug-assertions'

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      config/libwallet/api:
        CI_JOB: test
        CI_JOB_ARGS: config libwallet api
      impls:
        CI_JOB: test
        CI_JOB_ARGS: impls
      controller/all:
        CI_JOB: test
        CI_JOB_ARGS: controller .
      release:
        CI_JOB: release
        PLATFORM: linux-amd64
  steps:
    - template: '.ci/test.yml'
    - template: '.ci/release.yml'
- job: macos
  pool:
    vmImage: macos-latest
  strategy:
    matrix:
      test:
        CI_JOB: test-all
      release:
        CI_JOB: release
        PLATFORM: macos
  steps:
    - script: |
        brew uninstall llvm
      displayName: macOS Uninstall LLVM
    - template: '.ci/test.yml'
    - template: '.ci/release.yml'
- job: windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      test:
        CI_JOB: test-all
      release:
        CI_JOB: release
        PLATFORM: win-x64
  steps:
    - script: |
        choco install -y llvm
      displayName: Windows Install LLVM
    - template: '.ci/test.yml'
    - template: '.ci/windows-release.yml'
