name: Continuous Integration
on: [push, pull_request]

jobs:
  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - run: rustup toolchain install 1.99.0 --profile minimal --component clippy
      - run: cargo +1.99.0 clippy --workspace --all-targets -- -D warnings

  # Run tests alongside Clippy, even if lint fails
  linux-tests:
    name: Linux Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_args: [api, config, controller, impls, libwallet, .]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Test ${{ matrix.job_args }}
        working-directory: ${{ matrix.job_args }}
        run: cargo test --release

  macos-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Tests
        run: cargo test --release --all

  windows-tests:
    name: Windows Tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Tests
        run: cargo test --release --all
