name: "Continuous Integration"
on: [push]

jobs:
  linux:
    name: Linux CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_args: ["api", "config", "controller", "impls", "libwallet", "."]
    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.job_args }}
        env:
          CI_JOB_ARGS: ${{ matrix.job_args }}
        run: |
          for dir in ${CI_JOB_ARGS}; do
            printf "executing tests in directory \`%s\`...\n" "${dir}"
            cd "${dir}" && \
            cargo test --release && \
            cd - > /dev/null || exit 1
          done
  macos:
    name: macOS CI
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all

  windows:
    name: Windows CI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all
